spring:
  application:
    name: simulator
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 200MB
#server
server:
  port: 18080

opts:
  endpoints: "/login, /login, /login, /login, /login, /login, /login, /users, /users, /users, /users/{id},/register, 
  /register, /logout, /logout, /logout, /logout"
  request_rate: 1000
  request_rate_uncertainty: 70
  latency_min: 10
  latency_p50: 25
  latency_p90: 150
  latency_p99: 750
  latency_max: 10000
  latency_uncertainty: 70
  error_rate: 1
  spike_start_chance: 5
  spike_end_chance: 30

management:
  security:
    enabled: false
  server:
    port: 18088 # \u4FEE\u6539actuator\u7684\u7AEF\u53E3
  metrics:
    export:
      prometheus:
        enabled: true
        step: 1m
        descriptions: true
  web:
    server:
      auto-time-requests: true
  endpoints:
    prometheus:
      id: springmetrics
    web:
      #base-path: /xueqiu # \u4FEE\u6539actuator\u7684\u8DEF\u5F84\u540D
      exposure:
        include: health,prometheus
        exclude: info,env,metrics,httptrace,threaddump,heapdump

logging:
  level:
    root: INFO